version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: 'husky'
      - dependency-name: '@types/node'
      - dependency-name: 'aws-cdk'
      - dependency-name: '@aws-cdk'
