trigger:
  branches:
    include:
      - master

jobs:
  - job:
    displayName: 'Build'
    steps:
      - script: yarn --production
        workingDirectory: 'packages/app'
        name: 'yarnInstall'
        displayName: 'Yarn Install'
      - script: yarn build
        workingDirectory: 'packages/app'
        name: 'gaysbyBuild'
        displayName: 'Gatsby Build'
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true
      - task: PublishBuildArtifacts@1
