trigger:
  branches:
    include:
      - master

jobs:
  - job:
    displayName: 'Build Job'
    steps:
      - script: yarn --production
        workingDirectory: 'packages/app'
        name: 'build'
