trigger:
  branches:
    include:
      - master

jobs:
  - job:
    displayName: 'Build'
    steps:
      - script: echo 'it is $(storageAccountName) and $(accountSubscription)'
      - script: yarn --production
        workingDirectory: 'packages/app'
        name: 'yarnInstall'
        displayName: 'Yarn Install'
      - script: yarn build
        workingDirectory: 'packages/app'
        name: 'gatsbyBuild'
        displayName: 'Gatsby Build'
      - task: AzureCLI@2
        displayName: Deploy
        inputs:
          azureSubscription: $(accountSubscription)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: az storage blob upload-batch --account-name $(storageAccountName) --source ./public --destination '$web'
