trigger:
  branches:
    include:
      - master

jobs:
  - job:
    displayName: 'Build Job'
    steps:
      - script: yarn --production
        workingDirectory: 'packages/app'
        name: 'yarnInstall'
        displayName: 'Yarn Install'
      - script: yarn build
        workingDirectory: 'packages/app'
        name: 'gaysbyBuild'
        displayName: 'Gatsby Build'
