name: Build

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-16.04

    steps:
      - name: 'Checking out from GitHub'
        uses: 'actions/checkout@v2'

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn

      - name: Prettier
        run: yarn format

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn tsc:repo

      - name: Unit tests
        run: |
          yarn test
          bash <(curl -s https://codecov.io/bash)
