name: E2E

on:
  push:
    branches:
      - master

jobs:
  e2e:
    runs-on: ubuntu-16.04
    steps:
      - name: 'Checking out from GitHub'
        uses: 'actions/checkout@v2'

      # - name: Sleep 5 mins
      #   uses: jakejarvis/wait-action@master
      #   with:
      #     time: '5m'

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: true
          working-directory: packages/e2e
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
          CYPRESS_BASE_URL: https://bertie.dev
