name: Lighthouse Reports

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    name: Lighthouse Audit

    steps:
      - name: 'Checking out from GitHub'
        uses: 'actions/checkout@v2'

      - name: 'Generate badges'
        run: npx lighthouse-badges --urls https://bertie.dev -o lighthouse

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.1
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          title: 'Updates Lighthouse Badges'
          commit-message: 'Updates Lighthouse Badges'
          labels: lighthouse
          branch: update-lighthouse-badge
          branch-suffix: timestamp
