name: Master

on: push

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - name: 'Checking out from GitHub'
        uses: 'actions/checkout@v2'

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: packages/app/node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        working-directory: packages/app
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn

      - name: Gatsby build
        working-directory: packages/app
        run: yarn build

  test:
    runs-on: ubuntu-16.04

    steps:
      - name: 'Checking out from GitHub'
        uses: 'actions/checkout@v2'

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: |
            node_modules
            packages/**/node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Lerna bootstrap
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npx lerna bootstrap

      - name: Prettier
        run: yarn format

      - name: Lint
        run: yarn lint

      - name: Type check
        run: |
          yarn tsc:app
          yarn tsc:e2e

      - name: Unit tests
        working-directory: packages/app
        run: yarn test
