name: Master

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build, Test & Upload
    env:
      AWS_REGION: us-east-1

    steps:
      - name: 'Checking out from GitHub'
        uses: 'actions/checkout@v2'

      - name: Get PR author
        id: get-pr-author
        uses: actions/github-script@v3
        with:
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/__scripts__/get-merge-author.js`)
            script({github,context})

      - name: Log things
        run: echo ${{ steps.get-pr-author.outputs.author }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn

      - name: Unit tests
        run: |
          yarn test:ci
          bash <(curl -s https://codecov.io/bash)

      - name: Gatsby Build
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          ANALYTICS_TRACKING_ID: ${{ secrets.ANALYTICS_TRACKING_ID }}
        run: npm run build-ci

      - name: S3 Deploy
        run: |
          aws s3 rm "s3://${{ secrets.AWS_S3_BUCKET_NAME }}" --recursive
          aws s3 sync public "s3://${{ secrets.AWS_S3_BUCKET_NAME }}"
