name: Master

on:
  push:
    branches:
      - s3-deploy

jobs:
  test:
    runs-on: ubuntu-16.04
    name: Quality Checks
    env:
      AWS_REGION: us-east-1

    steps:
      - name: 'Checking out from GitHub'
        uses: 'actions/checkout@v2'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn

      - name: Unit tests
        run: |
          yarn test:ci
          bash <(curl -s https://codecov.io/bash)

      - name: S3 Deploy
        run: |
          aws s3 rm "s3://${{ secrets.AWS_S3_BUCKET_NAME }}" --recursive
          aws s3 sync public "s3://${{ secrets.AWS_S3_BUCKET_NAME }}"
