name: Master

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build, Test & Upload
    env:
      AWS_REGION: eu-west-2

    steps:
      - name: 'Checking out from GitHub'
        uses: 'actions/checkout@v2'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy previous build to rollback directory
        env:
          RUN_NUMBER: ${{ github.run_number }}
        run: aws s3 sync s3://bertie-blackman-artifacts/www s3://bertie-blackman-artifacts/www-rollback/$(($RUN_NUMBER - 1))

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Yarn install
        run: yarn

      - name: Unit tests
        run: |
          yarn test:ci
          bash <(curl -s https://codecov.io/bash)

      - name: Gatsby Build
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          ANALYTICS_TRACKING_ID: ${{ secrets.ANALYTICS_TRACKING_ID }}
        run: npm run build-ci

      - name: CDK deploy
        working-directory: cdk
        run: yarn deploy
