name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-16.04
    name: Gatsby Build

    steps:
      - name: 'Checking out from GitHub'
        uses: 'actions/checkout@v2'

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn

      - name: Gatsby build
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          ANALYTICS_TRACKING_ID: ${{ secrets.ANALYTICS_TRACKING_ID }}
        run: yarn build

  storybook:
    runs-on: ubuntu-16.04
    name: Storybook Build

    steps:
      - name: 'Checking out from GitHub'
        uses: 'actions/checkout@v2'

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn

      - name: Storybook build
        run: yarn build-storybook

  test:
    runs-on: ubuntu-16.04
    name: Quality Checks

    steps:
      - name: 'Checking out from GitHub'
        uses: 'actions/checkout@v2'

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn

      - name: Prettier
        run: yarn prettier:check

      - name: Lint
        run: yarn lint

      - name: Type check
        run: yarn tsc:repo

      - name: Unit tests
        run: |
          yarn test:ci
          bash <(curl -s https://codecov.io/bash)
